from __future__ import annotations

import io
from datetime import datetime
from typing import Any
import numpy as np
import pandas as pd

from backend.session.state import SessionState
from backend.services.dataset_service import to_json_compatible
from modules.insights import generate_statistical_insights


def generate_html_report(
    session: SessionState,
    include_sample: bool = True,
    include_stats: bool = True,
    include_insights: bool = True,
) -> str:
    df = session.get_active_df()
    name = session.active_dataset or "Dataset"
    if df is None:
        raise ValueError("No active dataset to generate report for.")

    static_insights = generate_statistical_insights(df)
    ai_insights = session.last_insights or {}

    numeric = df.select_dtypes(include=np.number)
    stats_html = numeric.describe().round(4).to_html(classes="table") if not numeric.empty and include_stats else ""
    sample_html = df.head(20).to_html(classes="table", index=False) if include_sample else ""
    missing_html = df.isnull().sum().reset_index().rename(columns={"index": "Column", 0: "Missing"}).to_html(classes="table", index=False)

    insights_section = ""
    if include_insights and ai_insights:
        exec_sum = ai_insights.get("executive_summary", "")
        findings = "".join(f"<li>{f}</li>" for f in ai_insights.get("key_findings", []))
        recs = "".join(f"<li>{r}</li>" for r in ai_insights.get("recommendations", []))
        insights_section = f"""
        <h2>🤖 AI Business Insights</h2>
        <div class='card'><p>{exec_sum}</p></div>
        <h3>Key Findings</h3><ul>{findings}</ul>
        <h3>Recommendations</h3><ul>{recs}</ul>
        """

    static_items = "".join(f"<li>{i}</li>" for i in static_insights)

    return f"""<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='UTF-8'>
<title>DataAgent Report: {name}</title>
<style>
  body {{ font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #0e1117; color: #e2e8f0; margin: 0; padding: 2rem; }}
  h1 {{ color: #4f8ef7; border-bottom: 2px solid #4f8ef7; padding-bottom: 0.5rem; }}
  h2 {{ color: #10b981; margin-top: 2rem; }}
  h3 {{ color: #f59e0b; }}
  .card {{ background: #1a1d24; border: 1px solid #2d3748; border-radius: 8px; padding: 1rem; margin: 1rem 0; }}
  .kpi-row {{ display: flex; gap: 1rem; flex-wrap: wrap; margin: 1rem 0; }}
  .kpi {{ background: #1a2744; border: 1px solid #4f8ef7; border-radius: 8px; padding: 1rem 1.5rem; min-width: 150px; }}
  .kpi .value {{ font-size: 2rem; font-weight: 700; color: #4f8ef7; }}
  .kpi .label {{ color: #718096; font-size: 0.85rem; }}
  .table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.85rem; }}
  .table th {{ background: #1a2744; color: #4f8ef7; padding: 0.5rem; text-align: left; }}
  .table td {{ border: 1px solid #2d3748; padding: 0.4rem 0.6rem; }}
  .table tr:nth-child(even) {{ background: #161a21; }}
  footer {{ margin-top: 3rem; color: #718096; font-size: 0.8rem; border-top: 1px solid #2d3748; padding-top: 1rem; }}
</style>
</head>
<body>
<h1>📊 Data Analyst Agent Report</h1>
<p style='color:#718096'>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Dataset: <strong>{name}</strong></p>

<h2>📋 Dataset Overview</h2>
<div class='kpi-row'>
  <div class='kpi'><div class='value'>{len(df):,}</div><div class='label'>Total Rows</div></div>
  <div class='kpi'><div class='value'>{len(df.columns)}</div><div class='label'>Columns</div></div>
  <div class='kpi'><div class='value'>{df.isnull().sum().sum():,}</div><div class='label'>Missing Values</div></div>
  <div class='kpi'><div class='value'>{df.duplicated().sum():,}</div><div class='label'>Duplicate Rows</div></div>
  <div class='kpi'><div class='value'>{len(df.select_dtypes(include=np.number).columns)}</div><div class='label'>Numeric Cols</div></div>
</div>

<h2>🔍 Quick Insights</h2>
<ul>{static_items}</ul>

{"<h2>📊 Statistical Summary</h2><div class='card'>" + stats_html + "</div>" if include_stats and stats_html else ""}

<h2>⚠️ Missing Values</h2>
<div class='card'>{missing_html}</div>

{"<h2>📋 Data Sample (First 20 Rows)</h2><div style='overflow-x:auto'>" + sample_html + "</div>" if include_sample and sample_html else ""}

{insights_section}

<footer>Generated by Data Analyst Agent | Production React + FastAPI Edition</footer>
</body>
</html>"""


def generate_excel_report(session: SessionState) -> bytes:
    df = session.get_active_df()
    if df is None:
        raise ValueError("No active dataset to generate Excel report for.")

    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        # Sheet 1: Data
        df.to_excel(writer, sheet_name="Data", index=False)

        # Sheet 2: Statistics
        numeric = df.select_dtypes(include=np.number)
        if not numeric.empty:
            numeric.describe().round(4).to_excel(writer, sheet_name="Statistics")

        # Sheet 3: Missing Values
        missing_df = df.isnull().sum().reset_index()
        missing_df.columns = ["Column", "Missing Count"]
        missing_df["Missing %"] = (missing_df["Missing Count"] / max(len(df), 1) * 100).round(2)
        missing_df.to_excel(writer, sheet_name="Missing Values", index=False)

        # Sheet 4: Column Info
        col_info = []
        for col in df.columns:
            col_info.append({
                "Column": col,
                "Dtype": str(df[col].dtype),
                "Missing": int(df[col].isnull().sum()),
                "Unique": int(df[col].nunique()),
                "Sample": str(df[col].dropna().iloc[0]) if len(df[col].dropna()) > 0 else "",
            })
        pd.DataFrame(col_info).to_excel(writer, sheet_name="Column Info", index=False)

        # Sheet 5: Query History
        history = session.query_history
        if history:
            hist_df = pd.DataFrame([
                {
                    "Timestamp": e["timestamp"].isoformat() if hasattr(e["timestamp"], "isoformat") else str(e["timestamp"]),
                    "Question": e["question"],
                    "Dataset": e.get("dataset", ""),
                    "Route": e.get("route", ""),
                }
                for e in history
            ])
            hist_df.to_excel(writer, sheet_name="Query History", index=False)

    return output.getvalue()


def generate_quick_profile(session: SessionState) -> dict[str, Any]:
    df = session.get_active_df()
    name = session.active_dataset or "Dataset"
    if df is None:
        raise ValueError("No active dataset.")

    numeric = df.select_dtypes(include=np.number)
    cat = df.select_dtypes(include="object")

    numeric_profiles = []
    if not numeric.empty:
        for col in numeric.columns:
            s = numeric[col].dropna()
            numeric_profiles.append({
                "column": col,
                "count": len(s),
                "mean": round(float(s.mean()), 4) if not s.empty else None,
                "std": round(float(s.std()), 4) if not s.empty else None,
                "min": float(s.min()) if not s.empty else None,
                "25%": float(s.quantile(0.25)) if not s.empty else None,
                "50%": float(s.median()) if not s.empty else None,
                "75%": float(s.quantile(0.75)) if not s.empty else None,
                "max": float(s.max()) if not s.empty else None,
                "skew": round(float(s.skew()), 3) if not s.empty else None,
                "kurtosis": round(float(s.kurtosis()), 3) if not s.empty else None,
                "missing": int(numeric[col].isnull().sum()),
                "missing_pct": round(numeric[col].isnull().sum() / len(df) * 100, 1),
            })

    categorical_profiles = []
    if not cat.empty:
        for col in cat.columns:
            mode_val = str(df[col].mode()[0]) if df[col].notna().any() else ""
            mode_cnt = int(df[col].value_counts().iloc[0]) if df[col].notna().any() else 0
            categorical_profiles.append({
                "column": col,
                "unique_values": int(df[col].nunique()),
                "most_common": mode_val,
                "most_common_count": mode_cnt,
                "missing": int(df[col].isnull().sum()),
                "missing_pct": round(df[col].isnull().sum() / len(df) * 100, 1),
            })

    return to_json_compatible({
        "dataset_name": name,
        "rows": int(len(df)),
        "cols": int(len(df.columns)),
        "numeric_columns": numeric_profiles,
        "categorical_columns": categorical_profiles,
    })
